apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: longdh16/payment-service
          ports:
            - containerPort: 4003
              name: 'http'
            - containerPort: 5003
              name: 'grpc'
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
