apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - name: http
      protocol: TCP
      port: 4003 # Service port for HTTP
      targetPort: 4003 # Pod port for HTTP
    - name: grpc
      protocol: TCP
      port: 5003 # Service port for gRPC
      targetPort: 5003 # Pod port for gRPC
