apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  selector:
    matchLabels:
      app: payment-db
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:15.3
          ports:
            - containerPort: 5434
              name: 'postgres'
          env:
            - name: POSTGRES_DB
              value: payment
            - name: POSTGRES_USER
              value: payment
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            limits:
              memory: 256Mi
              cpu: '1'
