# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: payment-volume-claim
# spec:
#   volumeName: payment-volume
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 256Mi
