apiVersion: v1
kind: Service
metadata:
  name: payment-db-service
spec:
  type: NodePort
  selector:
    app: payment-db
  ports:
    - name: 'postgres'
      protocol: TCP
      port: 5434
      targetPort: 5432
      nodePort: 30434
