apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: longdh16/order-service
          ports:
            - containerPort: 4002
              name: 'http'
            - containerPort: 5002
              name: 'grpc'
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
