apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  selector:
    matchLabels:
      app: order-db
  replicas: 1
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: order-db
          image: postgres:15.3
          ports:
            - containerPort: 5433
              name: 'postgres'
          volumeMounts:
            - mountPath: '/var/lib/postgresql/data'
              name: order-data-storage
          env:
            - name: POSTGRES_DB
              value: order
            - name: POSTGRES_USER
              value: order
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            limits:
              memory: 256Mi
              cpu: '1'
      volumes:
        - name: order-data-storage
          persistentVolumeClaim:
            claimName: order-volume-claim
