apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  type: NodePort
  selector:
    app: product-catalog-service
  ports:
    - name: http
      protocol: TCP
      port: 4001 # Service port for HTTP
      targetPort: 4001 # Pod port for HTTP
    - name: grpc
      protocol: TCP
      port: 5001 # Service port for gRPC
      targetPort: 5001 # Pod port for gRPC
