apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-db
spec:
  selector:
    matchLabels:
      app: product-catalog-db
  replicas: 1
  template:
    metadata:
      labels:
        app: product-catalog-db
    spec:
      containers:
        - name: product-catalog-db
          image: postgres:15.3
          ports:
            - containerPort: 5432
              name: 'postgres'
          env:
            - name: POSTGRES_DB
              value: product-catalog
            - name: POSTGRES_USER
              value: product-catalog
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
