apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-catalog-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: product-catalog-volume-claim
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/data/product-catalog'
