apiVersion: v1
kind: Service
metadata:
  name: product-catalog-db-service
spec:
  type: NodePort
  selector:
    app: product-catalog-db
  ports:
    - name: 'postgres'
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30435
