name: api-gateway-ci-cd

on:
  push:
    paths:
      - 'Dockerfile'
      - 'src/api-gateway/**'
      - 'k8s/api-gateway/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_PWD}}

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v4.1.1
      #   with:
      #     context: ./src/api-gateway
      #     file: ./src/api-gateway/Dockerfile
      #     push: true
      #     tags: |
      #       ${{secrets.DOCKER_HUB_USER}}/api-gateway:latest
      - name: Build Docker image without cache
        run: |
          docker build --no-cache -t ${{secrets.DOCKER_HUB_USER}}/api-gateway:latest .
      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_HUB_USER}}/api-gateway:latest
  cd:
    runs-on: ubuntu-22.04
    needs: [ci]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{secrets.GKE_SA}}

      - name: 'Get GKE Credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{secrets.CLUSTER_NAME}}
          project_id: ${{secrets.PROJECT_ID}}
          location: ${{secrets.LOCATION}}

      - name: 'Deploy to GKE'
        run: |
          kubectl apply -f ./k8s/api-gateway
